### ISSUE TITLE
FCS import problem with Cytek Aurora

### ISSUE THREAD

**Issue by bpteague** [cytoflow/cytoflow#267]
Thank you for your bug report! Please fill out the following template.

PLATFORM (Mac, PC, Linux, other): Linux

OPERATING SYSTEM (eg OSX 10.7, Windows 8.1): Ubuntu 18

SEVERITY (Critical? Major? Minor? Enhancement?): Major

DESCRIPTION:
- What were you trying to do?

Import tubes (fcs file)

- What happened?

Tube would not import and error message was given. I think the error can be found in the log below, but I am pasting it below for convenience. I think this is a problem specific to FCS files generated on the Cytek Aurora. I have imported files from BD instruments without issue.

Error: AttributeError: 'CytoflowError' object has no attribute 'value'

Location: File "cytoflowgui/import_dialog.py", line 719, in _on_add_tubes

Thread: MainThread

- What did you expect to happen?

I expected the tube to be imported.

PACKAGE VERSIONS: ['python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:19:38) \n[GCC 7.3.0]', 'cytoflow 1.0', 'fcsparser 0.2.0', 'pandas 0.23.4', 'numpy 1.15.4', 'numexpr 2.6.8', 'bottleneck 1.2.1', 'seaborn 0.9.0', 'matplotlib 3.0.2', 'scipy 1.1.0', 'scikit-learn 0.20.1', 'statsmodels 0.9.0', 'pyface 6.0.0', 'envisage 4.7.0', 'traits 4.6.0', 'traitsui 6.0.0', 'nbformat 4.4.0', 'yapf 0.22.0', 'yaml 3.13']

DEBUG LOG: 2020-08-05 11:53:46,784 DEBUG:envisage.application:---------- application starting ----------
2020-08-05 11:53:46,784 DEBUG:envisage.plugin_manager:plugin envisage.core starting
2020-08-05 11:53:46,803 DEBUG:envisage.provider_extension_registry:extensions to <envisage.preferences> <[[], [], ['file:///home/dinky/cytoflow-1.0/cytoflowgui/preferences.ini'], ['file:///home/dinky/cytoflow-1.0/cytoflowgui/preferences.ini'], ['file:///home/dinky/cytoflow-1.0/cytoflowgui/preferences.ini'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
2020-08-05 11:53:46,804 DEBUG:apptools.preferences.preferences:loading preferences from </home/dinky/.enthought/edu.mit.synbio.cytoflow/preferences.ini>
2020-08-05 11:53:46,810 DEBUG:apptools.preferences.preferences:loading preferences from <<_io.BufferedReader name='/home/dinky/cytoflow-1.0/cytoflowgui/preferences.ini'>>
2020-08-05 11:53:46,811 DEBUG:apptools.preferences.preferences:loading preferences from <<_io.BufferedReader name='/home/dinky/cytoflow-1.0/cytoflowgui/preferences.ini'>>
2020-08-05 11:53:46,811 DEBUG:apptools.preferences.preferences:loading preferences from <<_io.BufferedReader name='/home/dinky/cytoflow-1.0/cytoflowgui/preferences.ini'>>
2020-08-05 11:53:46,827 DEBUG:envisage.provider_extension_registry:extensions to <envisage.class_load_hooks> <[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
2020-08-05 11:53:46,844 DEBUG:envisage.provider_extension_registry:extensions to <envisage.categories> <[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
2020-08-05 11:53:46,860 DEBUG:envisage.provider_extension_registry:extensions to <envisage.service_offers> <[[], [<envisage.service_offer.ServiceOffer object at 0x7f440a3f4db0>], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
2020-08-05 11:53:46,860 DEBUG:envisage.service_registry:service <1> registered envisage.ui.tasks.preferences_dialog.PreferencesDialog
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin envisage.core started
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin envisage.ui.tasks starting
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin envisage.ui.tasks started
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow starting
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow started
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow.tasbe starting
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow.tasbe started
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow.export starting
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow.export started
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram starting
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram started
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.scatterplot starting
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.scatterplot started
2020-08-05 11:53:46,860 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram2d starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram2d started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.density starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.density started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde1d starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde1d started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde2d starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde2d started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.radviz starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.radviz started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.parallel_coords starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.parallel_coords started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view_plugins.violin starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view_plugins.violin started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.barchart starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.barchart started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats1d starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats1d started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats2d starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats2d started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.table starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.table started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.import starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.import started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.threshold starting
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.threshold started
2020-08-05 11:53:46,861 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.quad starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.quad started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range2d starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range2d started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.polygon starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.polygon started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.ratio starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.ratio started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.channel_statistic starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.channel_statistic started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.transform_statistic starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.transform_statistic started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.binning starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.binning started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_1d starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_1d started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_2d starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_2d started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.density starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.density started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.kmeans starting
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.kmeans started
2020-08-05 11:53:46,862 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.flowpeaks starting
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.flowpeaks started
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.pca starting
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.pca started
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.autofluorescence starting
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.autofluorescence started
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_linear starting
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_linear started
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.beads_calibrate starting
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.beads_calibrate started
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.color_translation starting
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.color_translation started
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.tasbe starting
2020-08-05 11:53:46,863 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.tasbe started
2020-08-05 11:53:46,863 DEBUG:envisage.application:---------- application started ----------
2020-08-05 11:53:46,863 DEBUG:envisage.ui.tasks.tasks_application:Tasks state location is /home/dinky/.enthought/edu.mit.synbio.cytoflow/tasks/qt
2020-08-05 11:53:46,880 DEBUG:envisage.provider_extension_registry:extensions to <envisage.ui.tasks.tasks> <[[], [], [<envisage.ui.tasks.task_factory.TaskFactory object at 0x7f4408afeeb8>], [<envisage.ui.tasks.task_factory.TaskFactory object at 0x7f4408afef10>], [<envisage.ui.tasks.task_factory.TaskFactory object at 0x7f4408afef68>], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
2020-08-05 11:53:46,898 DEBUG:envisage.provider_extension_registry:extensions to <envisage.ui.tasks.task_extensions> <[[], [<envisage.ui.tasks.task_extension.TaskExtension object at 0x7f4408b0c6d0>], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
2020-08-05 11:53:46,911 DEBUG:envisage.provider_extension_registry:extensions to <edu.mit.synbio.cytoflow.op_plugins> <[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [<cytoflowgui.op_plugins.import_op.ImportPlugin object at 0x7f440a395308>], [<cytoflowgui.op_plugins.threshold.ThresholdPlugin object at 0x7f440a395360>], [<cytoflowgui.op_plugins.range.RangePlugin object at 0x7f440a3953b8>], [<cytoflowgui.op_plugins.quad.QuadPlugin object at 0x7f440a395410>], [<cytoflowgui.op_plugins.range2d.Range2DPlugin object at 0x7f440a395468>], [<cytoflowgui.op_plugins.polygon.PolygonPlugin object at 0x7f440a3954c0>], [<cytoflowgui.op_plugins.ratio.RatioPlugin object at 0x7f440a395518>], [<cytoflowgui.op_plugins.channel_stat.ChannelStatisticPlugin object at 0x7f440a395570>], [<cytoflowgui.op_plugins.xform_stat.TransformStatisticPlugin object at 0x7f440a3955c8>], [<cytoflowgui.op_plugins.binning.BinningPlugin object at 0x7f440a395620>], [<cytoflowgui.op_plugins.gaussian_1d.GaussianMixture1DPlugin object at 0x7f440a395678>], [<cytoflowgui.op_plugins.gaussian_2d.GaussianMixture2DPlugin object at 0x7f440a3956d0>], [<cytoflowgui.op_plugins.density.DensityGatePlugin object at 0x7f440a395728>], [<cytoflowgui.op_plugins.kmeans.KMeansPlugin object at 0x7f440a395780>], [<cytoflowgui.op_plugins.flowpeaks.FlowPeaksPlugin object at 0x7f440a3957d8>], [<cytoflowgui.op_plugins.pca.PCAPlugin object at 0x7f440a395830>], [<cytoflowgui.op_plugins.autofluorescence.AutofluorescencePlugin object at 0x7f440a395888>], [<cytoflowgui.op_plugins.bleedthrough_linear.BleedthroughLinearPlugin object at 0x7f440a3958e0>], [<cytoflowgui.op_plugins.bead_calibration.BeadCalibrationPlugin object at 0x7f440a395938>], [<cytoflowgui.op_plugins.color_translation.ColorTranslationPlugin object at 0x7f440a395990>], [<cytoflowgui.op_plugins.tasbe.TasbePlugin object at 0x7f440a3959e8>]]>
2020-08-05 11:53:46,925 DEBUG:envisage.provider_extension_registry:extensions to <edu.mit.synbio.cytoflow.view_plugins> <[[], [], [], [], [], [<cytoflowgui.view_plugins.histogram.HistogramPlugin object at 0x7f440a3f4e60>], [<cytoflowgui.view_plugins.scatterplot.ScatterplotPlugin object at 0x7f440a3f4eb8>], [<cytoflowgui.view_plugins.histogram_2d.Histogram2DPlugin object at 0x7f440a3f4f10>], [<cytoflowgui.view_plugins.density.DensityPlugin object at 0x7f440a3f4f68>], [<cytoflowgui.view_plugins.kde_1d.Kde1DPlugin object at 0x7f440a3f4fc0>], [<cytoflowgui.view_plugins.kde_2d.Kde2DPlugin object at 0x7f440a395048>], [<cytoflowgui.view_plugins.radviz.RadvizPlugin object at 0x7f440a3950a0>], [<cytoflowgui.view_plugins.parallel_coords.ParallelCoordinatesPlugin object at 0x7f440a3950f8>], [<cytoflowgui.view_plugins.violin.ViolinPlotPlugin object at 0x7f440a395150>], [<cytoflowgui.view_plugins.bar_chart.BarChartPlugin object at 0x7f440a3951a8>], [<cytoflowgui.view_plugins.stats_1d.Stats1DPlugin object at 0x7f440a395200>], [<cytoflowgui.view_plugins.stats_2d.Stats2DPlugin object at 0x7f440a395258>], [<cytoflowgui.view_plugins.table.TablePlugin object at 0x7f440a3952b0>], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
2020-08-05 11:53:47,567 DEBUG:root:LocalWorkflow._on_workflow_add_remove_items :: (0, [], [<WorkflowItem: ImportPluginOp>])
2020-08-05 11:53:47,619 DEBUG:root:LocalWorkflow._on_selected_changed :: (<cytoflowgui.workflow.Workflow object at 0x7f440a5afeb8>, 'selected', None, <WorkflowItem: ImportPluginOp>)
2020-08-05 11:53:47,621 DEBUG:root:FigureCanvasQTAggLocal.resizeEvent : (1076, 1063)
2020-08-05 11:53:47,624 DEBUG:root:FigureCanvasQTAggLocal.resizeEvent : (1076, 1043)
2020-08-05 11:53:47,633 DEBUG:root:FigureCanvasQTAggLocal.resizeEvent : (1009, 896)
2020-08-05 11:53:47,767 DEBUG:root:LocalWorkflow.recv_main :: APPLY_CALLED
2020-08-05 11:53:47,767 DEBUG:root:LocalWorkflow.recv_main :: UPDATE_WI
2020-08-05 11:53:47,767 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: WORKING
2020-08-05 11:53:47,744 DEBUG:root:RemoteWorkflow.recv_main :: ADD_ITEMS
2020-08-05 11:53:47,745 DEBUG:root:RemoteWorkflow._on_workflow_add_remove_items :: (0, [], [<RemoteWorkflowItem: ImportPluginOp>])
2020-08-05 11:53:47,747 DEBUG:root:RemoteWorkflow.recv_main :: SELECT
2020-08-05 11:53:47,747 DEBUG:root:WorkflowItem.apply :: <RemoteWorkflowItem: ImportPluginOp>
2020-08-05 11:53:47,747 DEBUG:root:RemoteWorkflow._workflow_item_changed :: (<RemoteWorkflowItem: ImportPluginOp>, 'icon', None, 59)
2020-08-05 11:53:47,747 DEBUG:root:RemoteWorkflow._workflow_item_changed :: (<RemoteWorkflowItem: ImportPluginOp>, 'status', 'invalid', 'applying')
2020-08-05 11:53:47,747 DEBUG:root:mpl_multiprocess_backend.new_figure_manager()
2020-08-05 11:53:47,749 DEBUG:root:FigureCanvasAggRemote.listen_for_remote :: DPI
2020-08-05 11:53:47,749 DEBUG:root:mpl_multiprocess_backend.new_figure_manager()
2020-08-05 11:53:47,750 DEBUG:root:RemoteWorkflow._workflow_item_changed :: (<RemoteWorkflowItem: ImportPluginOp>, 'op_error', '', 'Click "Set up experiment", then "Import!"')
2020-08-05 11:53:47,750 DEBUG:root:RemoteWorkflow._workflow_item_changed :: (<RemoteWorkflowItem: ImportPluginOp>, 'icon', 59, 40)
2020-08-05 11:53:47,750 DEBUG:root:RemoteWorkflow._workflow_item_changed :: (<RemoteWorkflowItem: ImportPluginOp>, 'status', 'applying', 'invalid')
2020-08-05 11:53:47,750 DEBUG:root:WorkflowItem.plot :: <RemoteWorkflowItem: ImportPluginOp>
2020-08-05 11:53:47,750 DEBUG:root:mpl_multiprocess_backend.show
2020-08-05 11:53:47,751 DEBUG:root:FigureCanvasAggRemote.draw()
2020-08-05 11:53:47,756 DEBUG:root:FigureCanvasAggRemote.send_to_remote
2020-08-05 11:53:47,757 DEBUG:root:FigureCanvasAggRemote.send_to_remote
2020-08-05 11:53:47,776 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: DRAW
2020-08-05 11:53:47,777 DEBUG:root:LocalWorkflow.recv_main :: UPDATE_WI
2020-08-05 11:53:47,781 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: WORKING
2020-08-05 11:53:47,797 DEBUG:root:LocalWorkflow.recv_main :: UPDATE_WI
2020-08-05 11:53:47,816 DEBUG:root:LocalWorkflow.recv_main :: PLOT_CALLED
2020-08-05 11:53:47,830 DEBUG:pyface.ui.qt4.gui:---------- starting GUI event loop ----------
2020-08-05 11:53:47,834 DEBUG:root:FigureCanvasQTAggLocal.send_to_remote: ('RESIZE', 10.73404255319149, 9.53191489361702)
2020-08-05 11:53:47,837 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:53:47,835 DEBUG:root:FigureCanvasAggRemote.listen_for_remote :: RESIZE
2020-08-05 11:53:47,835 DEBUG:root:FigureCanvasAggRemote.draw()
2020-08-05 11:53:47,849 DEBUG:root:FigureCanvasAggRemote.draw()
2020-08-05 11:53:47,851 DEBUG:root:FigureCanvasAggRemote.send_to_remote
2020-08-05 11:53:47,878 DEBUG:root:FigureCanvasAggRemote.send_to_remote
2020-08-05 11:53:47,888 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: DRAW
2020-08-05 11:53:47,889 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: WORKING
2020-08-05 11:53:47,889 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: WORKING
2020-08-05 11:53:47,889 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:53:49,259 DEBUG:root:FigureCanvasQTAggLocal.resizeEvent : (813, 782)
2020-08-05 11:53:49,265 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:53:49,287 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:53:49,460 DEBUG:root:FigureCanvasQTAggLocal.send_to_remote: ('RESIZE', 4.897590361445783, 4.710843373493976)
2020-08-05 11:53:49,461 DEBUG:root:FigureCanvasAggRemote.listen_for_remote :: RESIZE
2020-08-05 11:53:49,462 DEBUG:root:FigureCanvasAggRemote.draw()
2020-08-05 11:53:49,472 DEBUG:root:FigureCanvasAggRemote.draw()
2020-08-05 11:53:49,474 DEBUG:root:FigureCanvasAggRemote.send_to_remote
2020-08-05 11:53:49,490 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: DRAW
2020-08-05 11:53:49,493 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: WORKING
2020-08-05 11:53:49,493 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: WORKING
2020-08-05 11:53:49,486 DEBUG:root:FigureCanvasAggRemote.send_to_remote
2020-08-05 11:53:49,494 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:53:49,681 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:53:50,744 DEBUG:root:FigureCanvasQTAggLocal.resizeEvent : (1076, 1043)
2020-08-05 11:53:50,751 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:53:50,775 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:53:50,945 DEBUG:root:FigureCanvasQTAggLocal.send_to_remote: ('RESIZE', 11.446808510638299, 11.095744680851064)
2020-08-05 11:53:50,945 DEBUG:root:FigureCanvasAggRemote.listen_for_remote :: RESIZE
2020-08-05 11:53:50,946 DEBUG:root:FigureCanvasAggRemote.draw()
2020-08-05 11:53:50,974 DEBUG:root:FigureCanvasAggRemote.draw()
2020-08-05 11:53:50,985 DEBUG:root:FigureCanvasAggRemote.send_to_remote
2020-08-05 11:53:51,000 DEBUG:root:FigureCanvasAggRemote.send_to_remote
2020-08-05 11:53:51,011 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: DRAW
2020-08-05 11:53:51,011 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: WORKING
2020-08-05 11:53:51,011 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: WORKING
2020-08-05 11:53:51,011 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:53:51,856 DEBUG:root:LocalWorkflow._on_selected_changed :: (<cytoflowgui.workflow.Workflow object at 0x7f440a5afeb8>, 'selected', <WorkflowItem: ImportPluginOp>, None)
2020-08-05 11:53:51,862 DEBUG:root:RemoteWorkflow.recv_main :: SELECT
2020-08-05 11:53:53,112 DEBUG:root:LocalWorkflow._on_selected_changed :: (<cytoflowgui.workflow.Workflow object at 0x7f440a5afeb8>, 'selected', None, <WorkflowItem: ImportPluginOp>)
2020-08-05 11:53:53,118 DEBUG:root:RemoteWorkflow.recv_main :: SELECT
2020-08-05 11:53:53,118 DEBUG:root:WorkflowItem.plot :: <RemoteWorkflowItem: ImportPluginOp>
2020-08-05 11:53:53,118 DEBUG:root:mpl_multiprocess_backend.show
2020-08-05 11:53:53,118 DEBUG:root:FigureCanvasAggRemote.draw()
2020-08-05 11:53:53,127 DEBUG:root:LocalWorkflow.recv_main :: PLOT_CALLED
2020-08-05 11:53:53,134 DEBUG:root:FigureCanvasAggRemote.send_to_remote
2020-08-05 11:53:53,187 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: DRAW
2020-08-05 11:53:53,187 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: WORKING
2020-08-05 11:53:53,190 DEBUG:root:FigureCanvasQtAggLocal.paintEvent:
2020-08-05 11:54:33,376 DEBUG:root:Exception occurred in traits notification handler for object: <class 'object'>, trait: add_tubes, old value: <undefined>, new value: 0.
Traceback (most recent call last):
File "cytoflow/operations/import_op.py", line 568, in parse_tube
File "site-packages/fcsparser/api.py", line 541, in parse
File "site-packages/fcsparser/api.py", line 107, in __init__
File "site-packages/fcsparser/api.py", line 119, in load_file
File "site-packages/fcsparser/api.py", line 225, in read_text
fcsparser.api.ParserFeatureNotImplementedError: The first two characters were:
$B. The last two characters were: LP
Parser expects the same delimiter character in beginning and end of TEXT segment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "cytoflowgui/import_dialog.py", line 716, in _on_add_tubes
File "cytoflow/operations/import_op.py", line 579, in parse_tube
cytoflow.utility.cytoflow_errors.CytoflowError: FCS reader threw an error reading data for tube /home/dinky/mounts/skimcs/Dinky/IL10_reporter/FM_timecourse_1/Broad/LILP/Tube_001.fcs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
File "site-packages/traits/trait_notifiers.py", line%
===========================================

**Comment by bpteague** [comment]
Yep, that's definitely an issue with the parser. I have validated it on many files, but it's not exhausive. Could you please attach an example file to this bug report?  Thanks!

**Comment by bpteague** [comment]
Fixed by 20469a85db2a5320808f76ae4f414e1881d34e7f in cytoflow/fcsparser
