### ISSUE TITLE
build for Raspberry Pi OS (64-bit) fails

### ISSUE THREAD

**Issue by Georg-Auer** [cytoflow/cytoflow#344]
### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
Raspberry Pi OS (64-bit)
Kernel version: 5.15
Debian version: 11 (bullseye)
### SEVERITY (Critical? Major? Minor? Enhancement?):
Major
### DESCRIPTION:
I tried to install/build cytoflow for Raspberry Pi OS (64-bit), since no wheel for this OS is available.
After `sudo apt install swig
` the build continues until llvmlite, which is required in 0.36.0 version.
For 0.36.0 llvmlite, install of llvm-10 is required, which is not available for raspberry os 64-bit.
llvmlite 0.39.1 can be installed without problems, but cannot be used during build because of
`Collecting llvmlite<0.37,>=0.36.0rc1`

This is what i tried:
`pip3 install cytoflow`

I assume this is all happening because numba==0.53.1 is required. 0.56.3 can be installed via pip, but 0.53.1 is not available for the os and to build it llvmlite==0.36.0 and llvm-10 need to be installed.
I am thankful for any help on this, sadly building llvm-10 is not an easy option, and i need the 64-bit os version for other python libraries.
  
**Don't forget to attach the log file to this bug report!** 

```
pip3 install cytoflow
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cytoflow
  Using cached cytoflow-1.2-cp39-cp39-linux_aarch64.whl
Collecting scikit-learn==1.0.1
  Using cached scikit_learn-1.0.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (26.4 MB)
Requirement already satisfied: traitsui==7.2.1 in ./.local/lib/python3.9/site-packages (from cytoflow) (7.2.1)
Requirement already satisfied: pyface==7.3.0 in ./.local/lib/python3.9/site-packages (from cytoflow) (7.3.0)
Requirement already satisfied: matplotlib==3.5.0 in ./.local/lib/python3.9/site-packages (from cytoflow) (3.5.0)
Collecting statsmodels==0.13.0
  Using cached statsmodels-0.13.0-cp39-cp39-linux_aarch64.whl
Collecting bottleneck==1.3.2
  Using cached Bottleneck-1.3.2-cp39-cp39-linux_aarch64.whl
Requirement already satisfied: pandas==1.3.5 in ./.local/lib/python3.9/site-packages (from cytoflow) (1.3.5)
Requirement already satisfied: numpy==1.21.2 in ./.local/lib/python3.9/site-packages (from cytoflow) (1.21.2)
Requirement already satisfied: python-dateutil==2.8.2 in ./.local/lib/python3.9/site-packages (from cytoflow) (2.8.2)
Requirement already satisfied: yapf==0.30.0 in ./.local/lib/python3.9/site-packages (from cytoflow) (0.30.0)
Requirement already satisfied: natsort==7.1.1 in ./.local/lib/python3.9/site-packages (from cytoflow) (7.1.1)
Collecting nbformat==5.1.3
  Using cached https://www.piwheels.org/simple/nbformat/nbformat-5.1.3-py3-none-any.whl (178 kB)
Collecting numba==0.53.1
  Using cached numba-0.53.1-cp39-cp39-linux_aarch64.whl
Collecting envisage==6.0.1
  Using cached https://www.piwheels.org/simple/envisage/envisage-6.0.1-py3-none-any.whl (320 kB)
Requirement already satisfied: scipy==1.7.3 in ./.local/lib/python3.9/site-packages (from cytoflow) (1.7.3)
Requirement already satisfied: importlib-resources==5.2.0 in ./.local/lib/python3.9/site-packages (from cytoflow) (5.2.0)
Collecting seaborn==0.11.2
  Using cached https://www.piwheels.org/simple/seaborn/seaborn-0.11.2-py3-none-any.whl (279 kB)
Collecting camel==0.1.2
  Using cached https://www.piwheels.org/simple/camel/camel-0.1.2-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: traits==6.2.0 in ./.local/lib/python3.9/site-packages (from cytoflow) (6.2.0)
Requirement already satisfied: pyopengl==3.1.1a1 in ./.local/lib/python3.9/site-packages (from cytoflow) (3.1.1a1)
Collecting numexpr==2.8.1
  Using cached numexpr-2.8.1-cp39-cp39-linux_aarch64.whl
Requirement already satisfied: pyyaml in ./.local/lib/python3.9/site-packages (from camel==0.1.2->cytoflow) (6.0)
Collecting apptools
  Using cached https://www.piwheels.org/simple/apptools/apptools-5.2.0-py3-none-any.whl (229 kB)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from envisage==6.0.1->cytoflow) (52.0.0)
Requirement already satisfied: zipp>=3.1.0 in ./.local/lib/python3.9/site-packages (from importlib-resources==5.2.0->cytoflow) (3.9.0)
Requirement already satisfied: packaging>=20.0 in ./.local/lib/python3.9/site-packages (from matplotlib==3.5.0->cytoflow) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.9/site-packages (from matplotlib==3.5.0->cytoflow) (4.37.4)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib==3.5.0->cytoflow) (8.1.2)
Requirement already satisfied: setuptools-scm>=4 in ./.local/lib/python3.9/site-packages (from matplotlib==3.5.0->cytoflow) (7.0.5)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.9/site-packages (from matplotlib==3.5.0->cytoflow) (1.4.4)
Requirement already satisfied: pyparsing>=2.2.1 in ./.local/lib/python3.9/site-packages (from matplotlib==3.5.0->cytoflow) (3.0.9)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.9/site-packages (from matplotlib==3.5.0->cytoflow) (0.11.0)
Requirement already satisfied: ipython-genutils in ./.local/lib/python3.9/site-packages (from nbformat==5.1.3->cytoflow) (0.2.0)
Collecting jsonschema!=2.5.0,>=2.4
  Using cached https://www.piwheels.org/simple/jsonschema/jsonschema-4.16.0-py3-none-any.whl (83 kB)
Collecting jupyter-core
  Using cached https://www.piwheels.org/simple/jupyter-core/jupyter_core-4.11.1-py3-none-any.whl (88 kB)
Requirement already satisfied: traitlets>=4.1 in ./.local/lib/python3.9/site-packages (from nbformat==5.1.3->cytoflow) (5.5.0)
Collecting llvmlite<0.37,>=0.36.0rc1
  Using cached llvmlite-0.36.0.tar.gz (126 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pytz>=2017.3 in ./.local/lib/python3.9/site-packages (from pandas==1.3.5->cytoflow) (2022.5)
Requirement already satisfied: importlib-metadata in ./.local/lib/python3.9/site-packages (from pyface==7.3.0->cytoflow) (5.0.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil==2.8.2->cytoflow) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.local/lib/python3.9/site-packages (from scikit-learn==1.0.1->cytoflow) (3.1.0)
Collecting joblib>=0.11
  Using cached https://www.piwheels.org/simple/joblib/joblib-1.2.0-py3-none-any.whl (297 kB)
Requirement already satisfied: patsy>=0.5.2 in ./.local/lib/python3.9/site-packages (from statsmodels==0.13.0->cytoflow) (0.5.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in ./.local/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==5.1.3->cytoflow) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in ./.local/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==5.1.3->cytoflow) (22.1.0)
Requirement already satisfied: typing-extensions in /usr/lib/python3/dist-packages (from setuptools-scm>=4->matplotlib==3.5.0->cytoflow) (3.7.4.3)
Requirement already satisfied: tomli>=1.0.0 in ./.local/lib/python3.9/site-packages (from setuptools-scm>=4->matplotlib==3.5.0->cytoflow) (2.0.1)
Requirement already satisfied: configobj in ./.local/lib/python3.9/site-packages (from apptools->envisage==6.0.1->cytoflow) (5.0.6)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      /usr/bin/python3 /tmp/pip-install-nce6gf1h/llvmlite_5f0b6719894044dbb770fde4d2d67855/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-nce6gf1h/llvmlite_5f0b6719894044dbb770fde4d2d67855/ffi/build.py", line 220, in <module>
          main()
        File "/tmp/pip-install-nce6gf1h/llvmlite_5f0b6719894044dbb770fde4d2d67855/ffi/build.py", line 210, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-nce6gf1h/llvmlite_5f0b6719894044dbb770fde4d2d67855/ffi/build.py", line 134, in main_posix
          raise RuntimeError(msg) from None
      RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
      error: command '/usr/bin/python3' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, jupyter-core, jsonschema, joblib, camel, bottleneck, scikit-learn, numexpr, numba, nbformat, statsmodels, seaborn, apptools, envisage, cytoflow
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.39.1
    Uninstalling llvmlite-0.39.1:
      Successfully uninstalled llvmlite-0.39.1
  Running setup.py install for llvmlite ... error
  error: subprocess-exited-with-error

  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running install
      running build
      got version from file /tmp/pip-install-nce6gf1h/llvmlite_5f0b6719894044dbb770fde4d2d67855/llvmlite/_version.py {'version': '0.36.0', 'full': 'e6bb8d137d922bec8beeb01a237254778759becd'}
      running build_ext
      /usr/bin/python3 /tmp/pip-install-nce6gf1h/llvmlite_5f0b6719894044dbb770fde4d2d67855/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-nce6gf1h/llvmlite_5f0b6719894044dbb770fde4d2d67855/ffi/build.py", line 220, in <module>
          main()
        File "/tmp/pip-install-nce6gf1h/llvmlite_5f0b6719894044dbb770fde4d2d67855/ffi/build.py", line 210, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-nce6gf1h/llvmlite_5f0b6719894044dbb770fde4d2d67855/ffi/build.py", line 134, in main_posix
          raise RuntimeError(msg) from None
      RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
      error: command '/usr/bin/python3' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of llvmlite
  Moving to /home/user64/.local/lib/python3.9/site-packages/llvmlite-0.39.1.dist-info/
   from /home/user64/.local/lib/python3.9/site-packages/~lvmlite-0.39.1.dist-info
  Moving to /home/user64/.local/lib/python3.9/site-packages/llvmlite/
   from /home/user64/.local/lib/python3.9/site-packages/~lvmlite
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

```

**Comment by bpteague** [comment]
Lol, good luck! Raspberry Pi is not a supported platform, and to be honest installing wheels is not particularly well tested. 

Based on the error output, I think you're right, that the llvm dependency is coming from numba. You might have better luck installing from source, [following the instrutions here.](https://cytoflow.readthedocs.io/en/stable/dev_manual/howto/install.html#to-hack-on-the-code). It's also possible that you would have better luck using conda -- I don't know what the conda/ARM support looks like. If you can get it to work, I'd certainly be curious -- feel free to report back here.

(Also, I'm spinning a new release with updated dependencies here in a few days. Might want to wait until then.)
