### ISSUE TITLE
Logical error

### ISSUE THREAD

**Issue by benweinberg89** [cytoflow/cytoflow#359]
### PLATFORM (Mac, PC, Linux, other):
Mac 

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
Mac OS 15.1

### SEVERITY (Critical? Major? Minor? Enhancement?):
Critical

### DESCRIPTION:
I gave 6bf2ca00755d4c5cf35bb8130758e2c306254021 a whirl and I'm getting this error even though I've put the logicle (from mCherry) in the right place:

```sh
(cf_dev) Bens-MacBook-Pro:cytoflow ben$ cd cytoflow/utility/logicle_ext
(cf_dev) Bens-MacBook-Pro:logicle_ext ben$ ls
FastLogicle.cpp			Logicle.i			__pycache__
LICENSE.txt			_Logicle.cpython-38-darwin.so	logicle.h
Logicle.cpp			__init__.py
(cf_dev) Bens-MacBook-Pro:logicle_ext ben$ python
Python 3.11.11 (main, Dec 11 2024, 10:28:39) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cytoflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ben/GitHub/cytoflow/cytoflow/__init__.py", line 49, in <module>
    from .utility.logging import MplFilter
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/__init__.py", line 38, in <module>
    from .scale import scale_factory, IScale, set_default_scale, get_default_scale
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/scale.py", line 206, in <module>
    import cytoflow.utility.logicle_scale  # @UnusedImport
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_scale.py", line 55, in <module>
    from .logicle_ext.Logicle import FastLogicle
ModuleNotFoundError: No module named 'cytoflow.utility.logicle_ext.Logicle'
```

I definitely ran the `export NO_LOGICLE=True` before the develop script too:
```sh
Bens-MacBook-Pro:cytoflow ben$ conda activate cf_dev
(cf_dev) Bens-MacBook-Pro:cytoflow ben$ export NO_LOGICLE=True
(cf_dev) Bens-MacBook-Pro:cytoflow ben$ python setup.py develop
```

**Comment by bpteague** [comment]
But you probably didn't follow the next instruction, which is to get a copy of `Logicle.so` or similar and install it where it needs to be. And the one from version 1.2, built with Python 3.8, won't work. I've attached the file you need to this comment. Download it, unzip,
[_Logicle.so.zip](https://github.com/user-attachments/files/18267841/_Logicle.so.zip)
 and copy into `cytoflow/utility/logicle_ext/`, per the installation instructions.

**Comment by benweinberg89** [comment]
Thanks @bpteague. Looks like I'm getting the same issue though:
```sh
(cf_dev) MacBookPro:cytoflow ben$ cd cytoflow/utility/logicle_ext/
(cf_dev) MacBookPro:logicle_ext ben$ ls
FastLogicle.cpp			Logicle.i			__pycache__
LICENSE.txt			_Logicle.cpython-311-darwin.so	logicle.h
Logicle.cpp			__init__.py
(cf_dev) MacBookPro:logicle_ext ben$ python
Python 3.11.11 (main, Dec 11 2024, 10:28:39) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cytoflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ben/GitHub/cytoflow/cytoflow/__init__.py", line 49, in <module>
    from .utility.logging import MplFilter
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/__init__.py", line 38, in <module>
    from .scale import scale_factory, IScale, set_default_scale, get_default_scale
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/scale.py", line 206, in <module>
    import cytoflow.utility.logicle_scale  # @UnusedImport
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_scale.py", line 55, in <module>
    from .logicle_ext.Logicle import FastLogicle
ModuleNotFoundError: No module named 'cytoflow.utility.logicle_ext.Logicle'
```

**Comment by benweinberg89** [comment]
Still some problems on 125332292815d9f76ee66c222c6e1c12602d8b93. Seems like maybe an Apple Silicon problem perhaps or wrong logicle file?

```
(cf_dev) Bens-MacBook-Pro:~ ben$ cd GitHub/cytoflow/cytoflow/utility/logicle_ext
(cf_dev) Bens-MacBook-Pro:logicle_ext ben$ ls
FastLogicle.cpp			Logicle.i			__init__.py
LICENSE.txt			Logicle.py			__pycache__
Logicle.cpp			_Logicle.cpython-311-darwin.so	logicle.h
(cf_dev) Bens-MacBook-Pro:logicle_ext ben$ python
Python 3.11.11 (main, Dec 11 2024, 10:28:39) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cytoflow
Traceback (most recent call last):
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/Logicle.py", line 13, in <module>
    import _Logicle
ImportError: dlopen(/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/_Logicle.cpython-311-darwin.so, 0x0002): tried: '/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/_Logicle.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/_Logicle.cpython-311-darwin.so' (no such file), '/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/_Logicle.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ben/GitHub/cytoflow/cytoflow/__init__.py", line 49, in <module>
    from .utility.logging import MplFilter
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/__init__.py", line 38, in <module>
    from .scale import scale_factory, IScale, set_default_scale, get_default_scale
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/scale.py", line 216, in <module>
    import cytoflow.utility.logicle_scale  # @UnusedImport
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_scale.py", line 55, in <module>
    from .logicle_ext.Logicle import FastLogicle
  File "/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/Logicle.py", line 15, in <module>
    from . import _Logicle
ImportError: dlopen(/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/_Logicle.cpython-311-darwin.so, 0x0002): tried: '/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/_Logicle.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/_Logicle.cpython-311-darwin.so' (no such file), '/Users/ben/GitHub/cytoflow/cytoflow/utility/logicle_ext/_Logicle.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by bpteague** [comment]
I spun version 1.2.1 last week. I've verified it works on an Apple Silicon Mac by the expedient of going out and buying a used one. Make sure you download the correct architecture from the Github release and *rename it to _Logicle.so* when you copy it to the place it needs to go.
